= 2D Library

image:https://travis-ci.com/CHARLONCyril/2D-Library.svg?branch=master["Build Status", link="https://travis-ci.com/CHARLONCyril/2D-Library"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the MIT License, with their permission.

= *Plan détaillé des différentes livraisons* :
 
Tâches à réaliser pour la *quatrième livraison* :

  * Nous allons tout d'abord corriger chacune des PR non validées afin que nous puissions les merger sur la branche master.
  * Puis nous souhaitons que la bibliothèque générée puisse être imprimée par l'utilisateur en format poster grâce a une fonctionalité: PrintPoster.
  
  * Enfin nous souhaitons pouvoir générer des QR codes qui renverrons sur les descriptions des livres de chaques utilisateurs.


*Déjà fait*:

*1ère livraison*

* Contract1 : Bouton plus / moins qui fonctionne correctement.
 
* Contract2 : Classe SearchData créée.

* Interface1 : Interface JavaSearcher créée.

* La fonctionnalité DrawBorder a été implémentée pour entourer les livres générés d'une bordure noire.

*2ème livraison*


 * Modification de l'interface JavaSearcher : modification du nom de la méthode getResultSearchData et suppression de la méthode getResultSearchDataLimited.
 * Création d'un objet qui fait des recherches.

 * Interface 2 : développement d'une classe SimpleSearcher qui implémente l'interface que nous avons utilisée lors de la première livraison JavaSearcher. On lui fourni une liste de livres qu'il cherche dans la bibliothèque déjà existante. 
 
 * WritePrefs : classe permettant la lecture et l'écriture des préférences d'affichage de l'utilisateur dans un fichier CSV.
 
 * GuiPrefs : GUI permettant d'éditer les préférences d'affichage de l'utilisateur (lecture d'un fichier CSV au démarrage, qu'on peut modifier)
 
 * L'interface graphique utilisateur GuiBooks développée après GuiPrefs et permettant d'éditer la liste de livres.
 
 * Elimination de la redondance de code, utilisation de lambda expressions afin de factoriser le code existant.
 
 * Rechargement automatique de la bibliothèque.
 
 *3ème livraison*
 
 * Nous avons tous d'abord intégré vos remarques de l'itération précédente :
    - Pour commencer, nous avons intégré au parsing du fichier CSV l'utilisation de la bibliothèque Univocity ce qui a grandement diminué la longeur de notre code et facilité la compréhension.
    
    - Puis nous avons apporté les modifications demandées à la classe SearchData afin qu'elle puisse stocker les données de recherche des utilistateurs. Pour ce faire, nous avons ajouté trois attributs : deux attributs de type String pour pouvoir effectuer des recherches sur le nom de l'auteur ou sur le titre du livre. Puis, nous avons créé une classe pour pouvoir stocker un interval de date afin de filter les livres en fonction de leur date de parution.
    
    - Ensuite, nous avons ajouté des liens pour effectuer une recherche sur les informations inscrites sur la tranche des livres. Cette partie fut assez difficle car au début nous avons essayé d'ajouter des liens après la génération du SVG, mais nous n'avons pas réussi à rajouter dans le SVG le lien associé au livre. Donc par soucis de productivité en s'inspirant du projet appelé "mido-svg", nous avons ajouté les liens avant la génération du svg. Néanmoins d'autres problèmes sont apparues comme la cohabitation entre le svg et le JFrame car il y avait des problèmes de compatbilité entre eux ce qui nous à fait perdre énormément de temps.
    
    - Enfin nous avons essayé de faire la migration de AWT vers SWT sans succés car nous aurions dû refaire l'intégralité de l'interface graphique.
 
 
 

