= 2D Library

image:https://travis-ci.com/CHARLONCyril/2D-Library.svg?branch=master["Build Status", link="https://travis-ci.com/CHARLONCyril/2D-Library"]


A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the MIT License, with their permission.
  
*PR effectuées durant l'Itération 2 :*
  
 ** #12 Add ClassDIagram for the second iteration -> girardet

 ** #11 Searchdata v2 -> CHARLONCyril & erictanggit 

 ** #10 Swing to AWT -> CHARLONCyril & erictanggit

 ** #9 Write prefs  ->   HenryJulienDesgranges & douhakarim
  
 ** #8 Update README.adoc -> girardet
  
   
*PR effectuées durant l'Itération 3 :*
  
 ** #14 Add link to svg library and dispay the svg on Jframe -> girardet & erictanggit 

 ** #13 Plan iteration 3 -> HenryJulienDesgranges

 ** #11 Searchdata v2 -> CHARLONCyril & douhakarim & erictanggit & girardet & HenryJulienDesgranges
  
 ** #9 Write prefs  ->   CHARLONCyril & douhakarim
