= 2D Library

image:https://travis-ci.com/CHARLONCyril/2D-Library.svg?branch=master["Build Status", link="https://travis-ci.com/CHARLONCyril/2D-Library"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the MIT License, with their permission.

= *Plan détaillé des différentes livraisons* :

Tâches à réaliser pour la *troisième livraison* :

  * Intégration des remarques sur l'itération précédente :
    - Utilisation de SWT à la place de AWT
    - Modification de la classe SearchData pour intégrer 3 attributs (AuthorRegExp : Recherche sur le nom de l'autheur; pubRange : intervalle de date de publication; titleRegExp : Recherche sur le titre) ce qui permettra une recherche plus poussée que celle qui existe actuellement. La GUI devra évoluer pour intégrer ces trois attributs (1 champs pour l'autheur, 1 champs pour le titre et 2 champs pour l'intervalle de date).
 
  * File2 : Nous voulons qu'il soit possible de déterminer l'épaisseur de chaque livre au lieu de fournir une hauteur et largeur pour avoir une représentation graphique plus réaliste.
  
  * Ressource1 : ajout d'une image illustrant le projet. 
  
  * DrawLinks : chaque livre se verra transformé en hyperlien qui dirigera l'utilisateur sur une recherche google associée au titre du livre.
  
  ___
 
 
Tâches à réaliser pour la *quatrième livraison* :

  * SearchCongress: Chaque utilisateur pourra faire une recherche sur le site de la bibliothèque du Congrès après avoir rentré ses critères de recherche.

  * Modification de GuiSearch afin d'y inclure la fonctionnalité SearchCongress (itération précédente).
  
  * La bibliothèque générée pourra être imprimée par l'utilisateur en format poster ou autre grâce a une fonctionalité: PrintPoster.
  
  * Enfin s'il nous reste du temps nous souhaitons que le livre recherché par l'utilisateur se mette en surbrillance s'il est présent dans la bibliothèque et développer un système de QR code qui permettra  à l'utilisateur d'avoir accèss à un résumé du livre.



*Déjà fait*:

*1ère livraison*

* Contract1 : Bouton plus / moins qui fonctionne correctement.
 
* Contract2 : Classe SearchData créée.

* Interface1 : Interface JavaSearcher créée.

* La fonctionnalité DrawBorder a été implémentée pour entourer les livres générés d'une bordure noire.

*2ème livraison*


 * Modification de l'interface JavaSearcher : modification du nom de la méthode getResultSearchData et suppression de la méthode getResultSearchDataLimited.
 * Création d'un objet qui fait des recherches.

 * Interface 2 : développement d'une classe SimpleSearcher qui implémente l'interface que nous avons utilisée lors de la première livraison JavaSearcher. On lui fourni une liste de livres qu'il cherche dans la bibliothèque déjà existante. 
 
 * WritePrefs : classe permettant la lecture et l'écriture des préférences d'affichage de l'utilisateur dans un fichier CSV.
 
 * GuiPrefs : GUI permettant d'éditer les préférences d'affichage de l'utilisateur (lecture d'un fichier CSV au démarrage, qu'on peut modifier)
 
 * L'interface graphique utilisateur GuiBooks développée après GuiPrefs et permettant d'éditer la liste de livres.
 
 * Elimination de la redondance de code, utilisation de lambda expressions afin de factoriser le code existant.
 
 * Rechargement automatique de la bibliothèque.
 
  ___
 
 

